
package ServerService;

import entity.StudentService.GradeService.*;

import javax.jws.*;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */

@WebService(name = "GradeServiceInterface", targetNamespace = "http://jw.nju.edu.cn/wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GradeServiceInterface {


    /**
     * 
     *                 输入学生学号，返回学号对应的学生的所有课程成绩
     *                 若查询成功则返回课程成绩，失败则返回相应的fault信息
     *             
     * 
     * @param studentNumber
     * @return
     *     returns entity.StudentService.GradeService.课程成绩列表类型
     * @throws CannotFindFault
     * @throws InvalidRequestFault
     */
    @WebMethod(action = "searchStudentGrade")
    @WebResult(name = "searchResponse", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "courseGradeListResponse")
    public 课程成绩列表类型 searchGrade(
            @WebParam(name = "searchRequest", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "studentNumber")
                    String studentNumber)
        throws CannotFindFault, InvalidRequestFault
    ;

    /**
     *
     *                 以课程成绩列表的形式输入待插入的成绩信息，对输入的信息执行插入操作，
     *                 若插入成功则返回插入的成绩信息；若已存在待插入的信息，则返回相应fault；请求信息有误则返回相应的fault
     *
     *
     * @param courseGradeListRequest
     * @return
     *     returns entity.StudentService.GradeService.课程成绩列表类型
     * @throws InvalidRequestFault
     * @throws AlreadyExistFault
     */
    @WebMethod(action = "addStudentGrade")
    @WebResult(name = "addResponse", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "courseGradeListResponse")
    public 课程成绩列表类型 addGrade(
            @WebParam(name = "addRequest", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "courseGradeListRequest")
                    课程成绩列表类型 courseGradeListRequest)
        throws AlreadyExistFault, InvalidRequestFault
    ;

    /**
     *
     *                 以课程成绩列表的形式输入修改信息，根据学号、课程号、成绩类型查询指定的成绩信息并修改，
     *                 若修改成功则返回修改后的信息，失败则返回相应的fault信息
     *
     *
     * @param courseGradeListRequest
     * @return
     *     returns entity.StudentService.GradeService.课程成绩列表类型
     * @throws CannotFindFault
     * @throws InvalidRequestFault
     */
    @WebMethod(action = "modifyStudentGrade")
    @WebResult(name = "modifyResponse", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "courseGradeListResponse")
    public 课程成绩列表类型 modifyGrade(
            @WebParam(name = "modifyRequest", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "courseGradeListRequest")
                    课程成绩列表类型 courseGradeListRequest)
        throws CannotFindFault, InvalidRequestFault
    ;

    /**
     *
     *                 以课程成绩列表的形式输入待删除的成绩信息，基于学号、课程成绩和成绩类型查找指定成绩并删除，
     *                 若删除成功则返回被删除的成绩信息；若未查询到待删除的信息，则返回相应fault；请求信息有误则返回相应的fault
     *
     *
     * @param courseGradeListRequest
     * @return
     *     returns entity.StudentService.GradeService.课程成绩列表类型
     * @throws CannotFindFault
     * @throws InvalidRequestFault
     */
    @WebMethod(action = "deleteStudentGrade")
    @WebResult(name = "deleteResponse", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "courseGradeListResponse")
    public 课程成绩列表类型 deleteGrade(
            @WebParam(name = "deleteRequest", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "courseGradeListRequest")
                    课程成绩列表类型 courseGradeListRequest)
        throws CannotFindFault, InvalidRequestFault
    ;

}
