
package com.example.webService.entity;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "StudentExistedFaultEle", targetNamespace = "http://jw.nju.edu.cn/wsdl/fault")
public class StudentExistedFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private StudentExistedFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public StudentExistedFault(String message, StudentExistedFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public StudentExistedFault(String message, StudentExistedFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: main.java.example.webService.StudentExistedFaultType
     */
    public StudentExistedFaultType getFaultInfo() {
        return faultInfo;
    }

}
