
package cn.edu.nju.jw.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import cn.edu.nju.jw.schema.学生类型;
import cn.edu.nju.schema.个人信息类型;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "addStudentInfoInterface", targetNamespace = "http://jw.nju.edu.cn/wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    cn.edu.nju.jw.schema.ObjectFactory.class,
    cn.edu.nju.schema.ObjectFactory.class
})
public interface AddStudentInfoInterface {


    /**
     * 
     *                 在这里完成需要增添的学生信息
     *                 若插入成功则返回插入的成绩信息；若已存在待插入的信息，则返回相应fault；请求信息有误则返回相应的fault
     *             
     * 
     * @param studentInfo
     * @return
     *     returns cn.edu.nju.schema.个人信息类型
     * @throws InvalidRequestFault
     * @throws AlreadyExistFault
     */
    @WebMethod(action = "addStudentGrade")
    @WebResult(name = "\u4e2a\u4eba\u4fe1\u606f", targetNamespace = "http://www.nju.edu.cn/schema", partName = "studentInfo")
    public 学生类型 addStudentInfoOperation(
        @WebParam(name = "\u5b66\u751f", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "studentInfo")
        学生类型 studentInfo)
        throws AlreadyExistFault, InvalidRequestFault
    ;

}
