
package cn.edu.nju.jw.wsdl;

import javax.jws.WebService;
import javax.xml.ws.BindingType;

import cn.edu.nju.jw.schema.学生类型;
import cn.edu.nju.schema.个人信息类型;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(portName = "searchStudentInfoEndpoint", serviceName = "StudentInfoManagementService", targetNamespace = "http://jw.nju.edu.cn/wsdl", endpointInterface = "cn.edu.nju.jw.wsdl.SearchStudentInfoInterface")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class StudentInfoManagementService_searchStudentInfoEndpointImpl
        implements SearchStudentInfoInterface {

    private RequestValidator validator;

    public StudentInfoManagementService_searchStudentInfoEndpointImpl() throws Exception {
        validator = new RequestValidator();
    }

    /**
     * 输入需要查询的学号，返回完整的学生信息
     * 若查询成功则返回课程成绩，失败则返回相应的fault信息
     *
     * @param studentNumber
     * @return returns cn.edu.nju.schema.个人信息类型
     * @throws CannotFindFault
     * @throws InvalidRequestFault
     */
    public 学生类型 searchStudentInfoOperation(String studentNumber)
            throws CannotFindFault, InvalidRequestFault {

        String validateMessage = validator.isValid(studentNumber);
        if (validateMessage != null) {
            throw new InvalidRequestFault(null, validateMessage);
        }

        学生类型 personInfo = DataUtil.get(studentNumber);
        if (personInfo == null) {
            throw new CannotFindFault(null, "Cannot Find");
        }
        return personInfo;
    }

}
