
package cn.edu.nju.jw.wsdl;

import javax.jws.WebService;
import javax.xml.ws.BindingType;

import cn.edu.nju.jw.schema.学生类型;
import cn.edu.nju.schema.个人信息类型;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(portName = "modifyStudentInfoEndpoint", serviceName = "StudentInfoManagementService", targetNamespace = "http://jw.nju.edu.cn/wsdl", endpointInterface = "cn.edu.nju.jw.wsdl.ModifyStudentInfoInterface")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class StudentInfoManagementService_modifyStudentInfoEndpointImpl
        implements ModifyStudentInfoInterface {

    private RequestValidator validator;

    public StudentInfoManagementService_modifyStudentInfoEndpointImpl() throws Exception {
        validator = new RequestValidator();
    }

    /**
     * 输入学生的个人信息，完成修改
     * 若修改成功则返回修改后的信息，失败则返回相应的fault信息
     *
     * @param studentInfo
     * @return returns cn.edu.nju.schema.个人信息类型
     * @throws CannotFindFault
     * @throws InvalidRequestFault
     */
    public 学生类型 modifyStudentInfoOperation(学生类型 studentInfo)
            throws CannotFindFault, InvalidRequestFault {

        String validateMessage = validator.isValid(studentInfo);
        if (validateMessage != null) {
            throw new InvalidRequestFault(null, validateMessage);
        }

        if (DataUtil.modify(studentInfo)) {
            return studentInfo;
        } else {
            throw new CannotFindFault("", "Cannot Find");
        }
    }

}
