
package cn.edu.nju.jw.wsdl;

import javax.jws.WebService;
import javax.xml.ws.BindingType;

import cn.edu.nju.jw.schema.学生类型;
import cn.edu.nju.schema.个人信息类型;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(portName = "deleteStudentInfoEndpoint", serviceName = "StudentInfoManagementService", targetNamespace = "http://jw.nju.edu.cn/wsdl", endpointInterface = "cn.edu.nju.jw.wsdl.DeleteStudentInfoInterface")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class StudentInfoManagementService_deleteStudentInfoEndpointImpl
        implements DeleteStudentInfoInterface {

    private RequestValidator validator;

    public StudentInfoManagementService_deleteStudentInfoEndpointImpl() throws Exception {
        validator = new RequestValidator();
    }

    /**
     * 输入需要删除的学生的个人信息，完成删除
     * 若删除成功则返回被删除的成绩信息；若未查询到待删除的信息，则返回相应fault；请求信息有误则返回相应的fault
     *
     * @param studentNumber
     * @return returns cn.edu.nju.schema.个人信息类型
     * @throws CannotFindFault
     * @throws InvalidRequestFault
     */
    public 学生类型 deleteStudentInfoOperation(String studentNumber)
            throws CannotFindFault, InvalidRequestFault {

        String validateMessage = validator.isValid(studentNumber);
        if (validateMessage != null) {
            throw new InvalidRequestFault(null, validateMessage);
        }

        学生类型 personInfo = DataUtil.delete(studentNumber);
        if (personInfo == null) {
            throw new CannotFindFault("", "Cannot Find");
        }
        return personInfo;
    }

}
