
package cn.edu.nju.jw.wsdl;

import javax.jws.WebService;
import javax.xml.ws.BindingType;

import cn.edu.nju.jw.schema.学生类型;
import cn.edu.nju.schema.个人信息类型;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(portName = "addStudentInfoEndpoint", serviceName = "StudentInfoManagementService", targetNamespace = "http://jw.nju.edu.cn/wsdl", endpointInterface = "cn.edu.nju.jw.wsdl.AddStudentInfoInterface")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class StudentInfoManagementService_addStudentInfoEndpointImpl
        implements AddStudentInfoInterface {

    private RequestValidator validator;

    public StudentInfoManagementService_addStudentInfoEndpointImpl() throws Exception {
        validator = new RequestValidator();
    }

    /**
     * 在这里完成需要增添的学生信息
     * 若插入成功则返回插入的成绩信息；若已存在待插入的信息，则返回相应fault；请求信息有误则返回相应的fault
     *
     * @param studentInfo
     * @return returns cn.edu.nju.schema.个人信息类型
     * @throws InvalidRequestFault
     * @throws AlreadyExistFault
     */
    public 学生类型 addStudentInfoOperation(学生类型 studentInfo)
            throws AlreadyExistFault, InvalidRequestFault {

        String validateMessage = validator.isValid(studentInfo);
        if (validateMessage != null) {

            throw new InvalidRequestFault(null, validateMessage);
        }

        if (DataUtil.add(studentInfo)) {
            return studentInfo;
        } else {

            throw new AlreadyExistFault(null, "Already Exist");
        }

    }

}
