
package com.example.webService.entity;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "PwdFaultEle", targetNamespace = "http://jw.nju.edu.cn/wsdl/fault")
public class PwdFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PwdFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public PwdFault(String message, PwdFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public PwdFault(String message, PwdFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: main.java.example.suck2.PwdFaultType
     */
    public PwdFaultType getFaultInfo() {
        return faultInfo;
    }

}
