
package cn.edu.nju.jw.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GradeService", targetNamespace = "http://jw.nju.edu.cn/wsdl", wsdlLocation = "file:/C:/Users/zyk/Desktop/SOA/assign10/SOA/assignment10/GradeService/GradeManagement.wsdl")
public class GradeService
    extends Service
{

    private final static URL GRADESERVICE_WSDL_LOCATION;
    private final static WebServiceException GRADESERVICE_EXCEPTION;
    private final static QName GRADESERVICE_QNAME = new QName("http://jw.nju.edu.cn/wsdl", "GradeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/zyk/Desktop/SOA/assign10/SOA/assignment10/GradeService/GradeManagement.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GRADESERVICE_WSDL_LOCATION = url;
        GRADESERVICE_EXCEPTION = e;
    }

    public GradeService() {
        super(__getWsdlLocation(), GRADESERVICE_QNAME);
    }

    public GradeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GRADESERVICE_QNAME, features);
    }

    public GradeService(URL wsdlLocation) {
        super(wsdlLocation, GRADESERVICE_QNAME);
    }

    public GradeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GRADESERVICE_QNAME, features);
    }

    public GradeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GradeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GradeServiceInterface
     */
    @WebEndpoint(name = "GradeServiceEndpoint")
    public GradeServiceInterface getGradeServiceEndpoint() {
        return super.getPort(new QName("http://jw.nju.edu.cn/wsdl", "GradeServiceEndpoint"), GradeServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GradeServiceInterface
     */
    @WebEndpoint(name = "GradeServiceEndpoint")
    public GradeServiceInterface getGradeServiceEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://jw.nju.edu.cn/wsdl", "GradeServiceEndpoint"), GradeServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GRADESERVICE_EXCEPTION!= null) {
            throw GRADESERVICE_EXCEPTION;
        }
        return GRADESERVICE_WSDL_LOCATION;
    }

}
